export const EMAIL_SUFFIX = [
	{ value: '@163.com' },
	{ value: '@139.com' },
	{ value: '@suhu.com' },
	{ value: '@qq.com' },
	{ value: '@189.cn' },
	{ value: '@126.com' },
	{ value: '@gmail.com' },
	{ value: '@sina.cn' },
	{ value: '@sina.com' },
	{ value: '@outlook.com' },
	{ value: '@hotmail.com' },
	{ value: '@aliyun.com' },
	{ value: '@tom.com' },
	{ value: '@sogou.com' },
	{ value: '@2980.com' },
	{ value: '@21cn.com' },
	{ value: '@188.com' },
	{ value: '@yeah.net' },
	{ value: '@vip.163.com' },
	{ value: '@foxmail.com' },
	{ value: '@wo.cn' },
	{ value: '@263.net.cn' },
];
